-- Insertar Ingredientes aleatorios
INSERT INTO ingrediente (nombre, precio, calorias, inventario, es_vegetariano, tipo_ingrediente_id) 
VALUES
('Fresa', 0.50, 30, 100, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Fruta')),
('Banana', 0.40, 50, 120, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Fruta')),
('Chocolate', 0.70, 80, 90, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Saborizante')),
('Vainilla', 0.60, 70, 85, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Saborizante')),
('Almendra', 0.80, 90, 70, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Frutos Secos')),
('Nuez', 0.85, 95, 60, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Frutos Secos')),
('Leche Condensada', 1.00, 150, 50, FALSE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Lácteo')),
('Crema de Avellanas', 1.20, 200, 40, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Untable')),
('Miel', 0.90, 130, 55, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Endulzante')),
('Coco Rallado', 0.75, 60, 80, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Fruta')),
('Mango', 0.55, 40, 110, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Fruta')),
('Piña', 0.50, 35, 115, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Fruta')),
('Caramelo', 0.65, 90, 75, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Saborizante')),
('Azúcar Morena', 0.30, 20, 140, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Endulzante')),
('Cacao en Polvo', 0.70, 100, 95, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Saborizante')),
('Jengibre', 0.45, 10, 130, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Especia')),
('Canela', 0.35, 15, 125, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Especia')),
('Menta', 0.40, 5, 120, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Hierba')),
('Galletas Trituradas', 0.80, 120, 65, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Topping')),
('Chispas de Chocolate', 0.90, 150, 60, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Topping')),
('Sirope de Fresa', 0.75, 140, 85, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Salsa')),
('Sirope de Chocolate', 0.80, 160, 80, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Salsa')),
('Sirope de Caramelo', 0.85, 170, 75, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Salsa')),
('Queso Crema', 1.10, 250, 45, FALSE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Lácteo')),
('Yogur Natural', 0.95, 100, 70, FALSE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Lácteo')),
('Helado de Vainilla', 1.50, 180, 40, FALSE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Helado')),
('Helado de Chocolate', 1.50, 190, 35, FALSE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Helado')),
('Helado de Fresa', 1.50, 175, 38, FALSE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Helado')),
('Helado de Mango', 1.60, 185, 32, FALSE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Helado')),
('Helado de Coco', 1.60, 195, 30, FALSE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Helado')),
('Galletas Oreo', 1.20, 200, 50, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Topping')),
('Nuez Moscada', 0.50, 10, 100, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Especia')),
('Avellanas', 0.90, 120, 60, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Frutos Secos')),
('Leche en Polvo', 0.80, 130, 70, FALSE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Lácteo')),
('Cereal Crujiente', 0.85, 140, 75, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Topping')),
('Mazapán', 1.00, 180, 65, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Dulce')),
('Frutas Secas', 1.20, 220, 55, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Frutos Secos')),
('Granola', 0.75, 160, 85, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Topping')),
('Marshmallows', 1.10, 170, 45, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Dulce')),
('Crema Batida', 1.30, 250, 35, FALSE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Lácteo')),
('Sirope de Miel', 0.95, 160, 90, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Salsa')),
('Chocolate Blanco', 1.40, 220, 40, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Chocolate')),
('Crema de Coco', 1.50, 260, 30, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Lácteo')),
('Jarabe de Maple', 1.25, 200, 55, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Salsa')),
('Frambuesa', 0.70, 50, 110, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Fruta')),
('Zanahoria Rallada', 0.45, 30, 120, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Verdura')),
('Mermelada de Frutas', 0.85, 180, 70, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Salsa')),
('Chía', 0.60, 90, 95, TRUE, (SELECT id FROM tipo_ingrediente WHERE nombre = 'Semilla'));

-- Insertar Productos aleatorios
INSERT INTO producto (nombre, precio_publico, tipo, heladeria_id) VALUES
('Copa de Chocolate', 5.50, 'Copa', 1),
('Malteada de Fresa', 4.80, 'Malteada', 1),
('Copa de Vainilla', 5.00, 'Copa', 1),
('Malteada de Mango', 5.20, 'Malteada', 1),
('Copa Tropical', 5.90, 'Copa', 1),
('Malteada de Coco', 5.10, 'Malteada', 1),
('Copa de Almendras', 6.20, 'Copa', 1),
('Malteada de Chocolate', 4.90, 'Malteada', 1),
('Copa de Avellanas', 6.50, 'Copa', 1),
('Malteada de Frutas', 5.30, 'Malteada', 1),
('Copa de Caramelo', 5.70, 'Copa', 1),
('Malteada de Galleta', 5.40, 'Malteada', 1),
('Copa de Menta', 6.00, 'Copa', 1),
('Malteada de Marshmallow', 5.80, 'Malteada', 1),
('Copa de Queso Crema', 6.30, 'Copa', 1),
('Malteada de Granola', 5.60, 'Malteada', 1),
('Copa de Mazapán', 6.40, 'Copa', 1),
('Malteada de Nuez', 5.70, 'Malteada', 1),
('Copa de Frambuesa', 6.10, 'Copa', 1),
('Malteada de Zanahoria', 5.50, 'Malteada', 1);